Vagrant.configure("2") do |config|
  config.vm.box = "mmckinst/dvwa"
  config.vm.box_version = "1.0.0"
  config.vm.network "forwarded_port", host: 8080, guest: 80
  config.vm.network "forwarded_port", host: 4444, guest: 4444
end
